[package]
name = "rusty-needle"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "3.0.0"
core-needle = { path = "../core-needle" }
